import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const exportReportToPDF = (data: any) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const dateStr = data.createdAt ? new Date(data.createdAt).toLocaleDateString() : new Date().toLocaleDateString();

    // Title
    doc.setFontSize(22);
    doc.setTextColor(255, 69, 0); // Primary color
    doc.text("Competitive Advantage Blueprint", 14, 22);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated by OpinionDeck on: ${dateStr}`, 14, 30);
    doc.line(14, 35, pageWidth - 14, 35);

    // 1. Market Attack Summary
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Strategic Directive", 14, 45);

    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Core Frustration:", 14, 52);
    doc.setFont("helvetica", "normal");
    const frustration = doc.splitTextToSize(data.market_attack_summary?.core_frustration || "N/A", pageWidth - 28);
    doc.text(frustration, 14, 58);

    let currentY = 58 + (frustration.length * 6);

    doc.setFont("helvetica", "bold");
    doc.text("Primary Competitor Failure:", 14, currentY + 5);
    doc.setFont("helvetica", "normal");
    const failure = doc.splitTextToSize(data.market_attack_summary?.primary_competitor_failure || "N/A", pageWidth - 28);
    doc.text(failure, 14, currentY + 11);

    currentY = currentY + 11 + (failure.length * 6);

    doc.setFont("helvetica", "bold");
    doc.text("Immediate Strike Opportunity:", 14, currentY + 5);
    doc.setFont("helvetica", "normal");
    const opportunity = doc.splitTextToSize(data.market_attack_summary?.immediate_opportunity || "N/A", pageWidth - 28);
    doc.text(opportunity, 14, currentY + 11);

    currentY = currentY + 11 + (opportunity.length * 6);

    // 2. High-Intensity Pain Points
    if (data.high_intensity_pain_points?.length > 0) {
        doc.setFontSize(16);
        doc.text("High-Intensity Pain Points", 14, currentY + 15);
        autoTable(doc, {
            startY: currentY + 20,
            head: [['Pain Point', 'Intensity', 'Mentions', 'Strategic Impact']],
            body: data.high_intensity_pain_points.map((p: any) => [
                p.title,
                p.intensity,
                `${p.mention_count} (${p.threads_covered} Threads)`,
                p.why_it_matters
            ]),
            theme: 'striped',
            headStyles: { fillColor: [239, 68, 68] } // Red
        });
        currentY = (doc as any).lastAutoTable.finalY;
    }

    // 3. Switch Triggers
    if (data.switch_triggers?.length > 0) {
        doc.setFontSize(16);
        doc.text("Switching Triggers", 14, currentY + 15);
        autoTable(doc, {
            startY: currentY + 20,
            head: [['Trigger', 'Signals', 'Strategic Implication']],
            body: data.switch_triggers.map((s: any) => [
                s.trigger,
                s.evidence_mentions,
                s.strategic_implication
            ]),
            theme: 'grid',
            headStyles: { fillColor: [79, 70, 229] } // Indigo
        });
        currentY = (doc as any).lastAutoTable.finalY;
    }

    // 4. Feature Gaps
    if (data.feature_gaps?.length > 0) {
        doc.setFontSize(16);
        doc.text("Feature Deficiencies", 14, currentY + 15);
        autoTable(doc, {
            startY: currentY + 20,
            head: [['Missing/Weak Feature', 'Demand', 'Opportunity Level']],
            body: data.feature_gaps.map((f: any) => [
                f.missing_or_weak_feature,
                f.demand_signal_strength,
                f.opportunity_level
            ]),
            theme: 'striped',
            headStyles: { fillColor: [245, 158, 11] } // Orange
        });
        currentY = (doc as any).lastAutoTable.finalY;
    }

    // 5. Weakness Map
    if (data.competitive_weakness_map?.length > 0) {
        doc.setFontSize(16);
        doc.text("Competitive Weakness Map", 14, currentY + 15);
        autoTable(doc, {
            startY: currentY + 20,
            head: [['Competitor', 'Perceived Weakness', 'Strike Plan']],
            body: data.competitive_weakness_map.map((w: any) => [
                w.competitor,
                w.perceived_weakness,
                w.exploit_opportunity
            ]),
            theme: 'grid',
            headStyles: { fillColor: [16, 185, 129] } // Green
        });
        currentY = (doc as any).lastAutoTable.finalY;
    }

    // 6. Build Roadmap
    if (data.ranked_build_priorities?.length > 0) {
        doc.setFontSize(16);
        doc.text("Strategic Build Roadmap", 14, currentY + 15);
        autoTable(doc, {
            startY: currentY + 20,
            head: [['Rank', 'Initiative', 'Impact', 'Justification']],
            body: data.ranked_build_priorities.map((b: any) => [
                `#${b.priority_rank}`,
                b.initiative,
                b.expected_impact,
                b.justification
            ]),
            theme: 'striped',
            headStyles: { fillColor: [255, 69, 0] } // Primary
        });
        currentY = (doc as any).lastAutoTable.finalY + 10;
    }

    // 6.5. 90-Day Launch Roadmap
    if (data.launch_velocity_90_days) {
        doc.setFontSize(16);
        doc.setTextColor(99, 102, 241); // Indigo
        doc.text("Tactical Launch Roadmap (90 Days)", 14, currentY + 10);
        doc.setTextColor(0, 0, 0);

        autoTable(doc, {
            startY: currentY + 15,
            body: [
                ['Core Feature to Ship', data.launch_velocity_90_days.core_feature_to_ship],
                ['Positioning Angle', data.launch_velocity_90_days.positioning_angle],
                ['Target Segment', data.launch_velocity_90_days.target_segment],
                ['Pricing Strategy', data.launch_velocity_90_days.pricing_strategy],
                ['Primary Differentiator', data.launch_velocity_90_days.primary_differentiator],
            ],
            theme: 'grid',
            styles: { fontSize: 10, cellPadding: 5 },
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } }
        });
        currentY = (doc as any).lastAutoTable.finalY;
    }

    // 7. Messaging Angles
    if (data.messaging_and_positioning_angles?.length > 0) {
        doc.setFontSize(16);
        doc.text("Messaging Leverage", 14, currentY + 15);
        autoTable(doc, {
            startY: currentY + 20,
            head: [['Angle', 'Emotional Driver', 'Evidence Quote']],
            body: data.messaging_and_positioning_angles.map((m: any) => [
                m.angle,
                m.supporting_emotional_driver,
                m.supporting_evidence_quotes?.[0] || "N/A"
            ]),
            theme: 'grid',
            headStyles: { fillColor: [37, 99, 235] } // Blue
        });
        currentY = (doc as any).lastAutoTable.finalY;
    }

    // 8. Risks
    if (data.risk_flags?.length > 0) {
        doc.setFontSize(16);
        doc.text("Intelligence Risks", 14, currentY + 15);
        autoTable(doc, {
            startY: currentY + 20,
            head: [['Risk', 'Evidence Basis']],
            body: data.risk_flags.map((r: any) => [r.risk, r.evidence_basis]),
            theme: 'striped',
            headStyles: { fillColor: [153, 27, 27] } // Dark Red
        });
        currentY = (doc as any).lastAutoTable.finalY;
    }

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - 25, doc.internal.pageSize.getHeight() - 10);
        doc.text("© 2026 OpinionDeck - Strategic Competitive Intelligence", 14, doc.internal.pageSize.getHeight() - 10);
    }

    const filename = `OpinionDeck_StrikePlan_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(filename);
};
